#!/usr/bin/env node
// Installs the optional status panel ae-mcp-panel.jsx into After Effects' "ScriptUI Panels" folder so it can be
// docked via the Window menu. Zero dependencies.
//
//   node install-panel.mjs              copy the panel into every installed AE version
//   node install-panel.mjs --link       install a small loader that runs the panel from this folder
//                                       (updates apply after reopening the panel, no reinstall; --dev is an alias)
//   node install-panel.mjs --uninstall  remove it
//   node install-panel.mjs --ae "C:\Program Files\Adobe\Adobe After Effects 2026"
//
// Program Files needs administrator rights: on Windows a UAC prompt appears.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const PANEL_NAME = "ae-mcp-panel.jsx";
const here = path.dirname(fileURLToPath(import.meta.url));
const panelSource = path.join(here, PANEL_NAME);

export function findAfterEffects(platform = process.platform) {
  const roots = platform === "win32"
    ? [path.join(process.env.ProgramFiles || "C:\\Program Files", "Adobe")]
    : ["/Applications"];
  const found = [];
  for (const root of roots) {
    let names = [];
    try { names = fs.readdirSync(root); } catch { continue; }
    for (const name of names) {
      if (!/^Adobe After Effects \d{4}/i.test(name)) continue;
      const dir = path.join(root, name);
      const exe = platform === "win32" ? path.join(dir, "Support Files", "AfterFX.exe") : path.join(dir, `${name}.app`);
      if (fs.existsSync(exe)) found.push(dir);
    }
  }
  return found.sort().reverse();
}

export function panelsFolder(aeDir, platform = process.platform) {
  return platform === "win32"
    ? path.join(aeDir, "Support Files", "Scripts", "ScriptUI Panels")
    : path.join(aeDir, "Scripts", "ScriptUI Panels");
}

export function loaderSource(panelPath) {
  const target = panelPath.replace(/\\/g, "/").replace(/[^\x20-\x7e]/g, ch => "\\u" + ch.charCodeAt(0).toString(16).padStart(4, "0"));
  return [
    "// AE MCP Bridge - loader (generated by install-panel.mjs --link).",
    "// Runs the panel from the bridge folder: updates apply after reopening the panel.",
    "(function (thisObj) {",
    `    var file = new File("${target.replace(/"/g, '\\"')}");`,
    "    if (!file.exists) { alert(\"AE MCP Bridge: panel not found at \" + file.fsName); return; }",
    "    $.global.aeMcpPanelHost = thisObj;",
    "    try { $.evalFile(file); } finally { $.global.aeMcpPanelHost = undefined; }",
    "})(this);",
    ""
  ].join("\n");
}

const psQuote = text => `'${text.replace(/'/g, "''")}'`;

// Runs a PowerShell script elevated (UAC prompt) and waits for it.
function runElevated(script) {
  const encoded = Buffer.from(script, "utf16le").toString("base64");
  const outer = `$p = Start-Process powershell -Verb RunAs -Wait -PassThru -WindowStyle Hidden -ArgumentList '-NoProfile','-EncodedCommand','${encoded}'; exit $p.ExitCode`;
  const result = spawnSync("powershell", ["-NoProfile", "-Command", outer], { stdio: "inherit" });
  return result.status === 0;
}

function writeTarget(target, content, uninstall) {
  try {
    if (uninstall) fs.rmSync(target, { force: true });
    else { fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, content); }
    return true;
  } catch (error) {
    if (!["EPERM", "EACCES"].includes(error.code)) throw error;
  }
  if (process.platform !== "win32") {
    const flags = process.argv.slice(2).map(a => (/\s/.test(a) ? `"${a}"` : a)).join(" ");
    console.error(`  No permission. Run it with sudo: sudo "${process.execPath}" "${fileURLToPath(import.meta.url)}" ${flags}`.trimEnd());
    return false;
  }
  console.log("  Administrator rights needed: confirm the Windows prompt (UAC)...");
  let script;
  if (uninstall) {
    script = `Remove-Item -LiteralPath ${psQuote(target)} -Force -ErrorAction SilentlyContinue`;
  } else {
    const temp = path.join(os.tmpdir(), `ae-mcp-panel-${process.pid}.jsx`);
    fs.writeFileSync(temp, content);
    script = `New-Item -ItemType Directory -Force -Path ${psQuote(path.dirname(target))} | Out-Null; ` +
      `Copy-Item -LiteralPath ${psQuote(temp)} -Destination ${psQuote(target)} -Force`;
  }
  const ok = runElevated(script);
  return ok && (uninstall ? !fs.existsSync(target) : fs.existsSync(target) && fs.readFileSync(target).equals(Buffer.from(content)));
}

function main(argv) {
  const dev = argv.includes("--link") || argv.includes("--dev");
  const uninstall = argv.includes("--uninstall");
  const aeIndex = argv.indexOf("--ae");
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(fs.readFileSync(fileURLToPath(import.meta.url), "utf8").split("\n").slice(1, 11).join("\n").replace(/^\/\/ ?/gm, ""));
    return 0;
  }
  const targets = aeIndex >= 0 ? [path.resolve(argv[aeIndex + 1] || "")] : findAfterEffects();
  if (!targets.length) {
    console.error("After Effects was not found. Pass its folder: --ae \"C:\\Program Files\\Adobe\\Adobe After Effects 2026\"");
    return 1;
  }
  const content = dev ? Buffer.from(loaderSource(panelSource)) : fs.readFileSync(panelSource);
  let failures = 0;
  for (const aeDir of targets) {
    const target = path.join(panelsFolder(aeDir), PANEL_NAME);
    console.log(`${uninstall ? "Removing" : dev ? "Installing loader to" : "Installing panel to"} ${target}`);
    if (writeTarget(target, content, uninstall)) console.log("  done");
    else { console.error("  FAILED"); failures++; }
  }
  if (!uninstall && !failures) {
    console.log("\nNext: restart After Effects, open Window > ae-mcp-panel.jsx. The panel is optional: it only shows a log.");
    console.log("Make sure Preferences > Scripting & Expressions > Allow Scripts to Write Files and Access Network is on.");
  }
  return failures ? 1 : 0;
}

const entry = process.argv[1] ? path.resolve(process.argv[1]).toLowerCase() : "";
if (entry === fileURLToPath(import.meta.url).toLowerCase()) process.exit(main(process.argv.slice(2)));
